language: go

env:
  global:
    - TRAVIS_TAG=v0.2.0

install:
  - gem install fpm

script:
  - go get -t -v ./...
  - go build -v
  - go test -v ./...

after_success:
#  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash -x
  - curl -sL https://git.io/goreleaser | bash -x

